project:
  type: book
  output-dir: _site

book:
  title: "cheac /btw"
  author:
    - "Jack Kirk Pedersen"
    - "Melissa Marks"
    - "Frederik Lizak Johansen"
    - "Ahmad Tirmidzi"
    - "Till Schertenleib"
  date: today
  search: true

  # Grouped navigation
  chapters:
    - index.qmd

    - part: "Advisory & Best Practices"
      chapters:
        - practices/manuscript-writing.qmd
        - practices/literature-search.qmd
        - practices/evaluating-output.qmd

    - part: "Archive: Case Studies"
      chapters:
        - cases/overview.qmd
        - cases/success-stories.qmd
        - cases/failure-modes.qmd
        - cases/contribute-a-case.qmd

    - part: "Governance & Policies"
      chapters:
        - guidlines/council-charter.qmd
        - guidlines/ku-guidelines.qmd
        - guidlines/data-privacy-ip.qmd
        - guidlines/publisher-standards.qmd
        - guidlines/transparency.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true