project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "*.md"
    - "!README.md"
    - "!AGENTS.md"
  resources:
    - documents/*.pdf
    - assets/logos/*
    - assets/figures/*
    - favicon.ico

website:
  title: "&#92;btw"
  favicon: assets/logos/cheac-logo-square-transparent.svg
  navbar:
    logo: assets/logos/cheac-logo-long-transparent.svg
    logo-alt: "CHEAC logo"
    background: light
    search: true
    left: 
      - href: index.qmd
        text: Home

      - href: practices/index.qmd
        text: "Best usage practices"
      - href: guidlines/index.qmd
        text: "Guidlines"
      - href: posts/index.qmd
        text: "Posts"
      - text: "Contributing"
        menu:
          - href: contributing/contributing.qmd
            text: Contributing
      - href: references.qmd
        text: References

bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    code-copy: true